version: '3.5'

services:
  klinikare-web:
    container_name: klinikare-web
    build:
      context: ./etc/nginx
      args:
        UID: $U_ID
    ports:
      - 250:80
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - klinikare-be
    networks:
      - klinikare-network

  klinikare-be:
    container_name: klinikare-be
    build:
      context: etc/php
      args:
        UID: $U_ID
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=klinikare

    volumes:
      - ./:/appdata/www
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    depends_on:
      - klinikare-db
    networks:
      - klinikare-network

  klinikare-db:
    container_name: klinikare-db
    build:
      context: ./etc/database
    ports:
      - 36000:3306
    environment:
      MYSQL_DATABASE: klinikare_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - klinikare-db-data:/var/lib/mysql
    networks:
      - klinikare-network

volumes:
    klinikare-db-data:

networks:
  klinikare-network:
    external: true
